# Generated by Django 5.0.6 on 2024-10-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParkingSpot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spot_number", models.CharField(max_length=10)),
                ("available", models.BooleanField(default=True)),
            ],
        ),
    ]
