# Generated by Django 5.0.6 on 2024-10-05 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("easypark", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parkingspot",
            old_name="available",
            new_name="is_available",
        ),
    ]
