# Generated by Django 5.0.6 on 2024-10-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("easypark", "0002_rename_available_parkingspot_is_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingspot",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="parkingspot",
            name="spot_number",
            field=models.IntegerField(unique=True),
        ),
    ]
