# Generated by Django 5.0.6 on 2024-10-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("easypark", "0003_parkingspot_details_alter_parkingspot_spot_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parkingspot",
            name="details",
        ),
        migrations.AddField(
            model_name="parkingspot",
            name="license_plate",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
