# Generated by Django 5.0.6 on 2024-10-07 12:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("easypark", "0005_parkingspot_reserved_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingspot",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="parkingspot",
            name="location",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
